/// <reference path="./KeyboardController.ts" />
var KeyboardController;
(function (KeyboardController) {
    KeyboardController.controlKeys = [
        "backspace",
        "tab",
        "q",
        "w",
        "e",
        "r",
        "t",
        "y",
        "u",
        "i",
        "o",
        "p",
        "[",
        "]",
        "a",
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l",
        ";",
        "\'",
        "caps_lock",
        "enter",
        "shift",
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        ",",
        ".",
        "/",
        "ctrl",
        "alt",
        "cmd",
        "space",
    ];
})(KeyboardController || (KeyboardController = {}));
